on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: set API key 
        run: echo "API_KEY=1235" >> GITHUB_ENV
      - name: using API key 
        run: |
          echo "::add-mask::API_KEY" 
          echo "using api key $API_KEY"
